remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Title of Site
description: Testing some leaderboard site templates

google_analytics: [Your Google Analytics tracking ID]